apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cfcd0rfsf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cfcd0rfsf-java-springboot-gitops